setup_commands:
  - Invoke-WebRequest -Uri "https://aka.ms/vs/stable/vs_buildtools.exe" -OutFile "$env:TEMP\vs_buildtools.exe"; Start-Process -FilePath "$env:TEMP\vs_buildtools.exe" -ArgumentList "--passive --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" -Wait

post_setup_commands:
  - pnpm add -g @google/gemini-cli
  - pnpm add -g @openai/codex

apps:
  - name: git
  - name: gh
  - name: 7zip
  - name: clash-verge-rev
    bucket: extras
    desktop_shortcut: true

  - name: pwsh
  - name: windows-terminal
    bucket: extras
    desktop_shortcut: true
  - name: k-lite-codec-pack-basic-np
    bucket: extras
  - name: diskgenius
    bucket: extras
    desktop_shortcut: true
  - name: everything
    bucket: extras

  - name: Readest
    bucket: extras
    desktop_shortcut: true
  - name: googlechrome
    bucket: extras
    desktop_shortcut: true
  - name: firefox
    bucket: extras
    desktop_shortcut: true
  - name: obsidian
    bucket: extras
    desktop_shortcut: true

  - name: localsend
    bucket: extras
    desktop_shortcut: true
  - name: enpass
    bucket: extras
  - name: stranslate
    bucket: extras
    desktop_shortcut: true

  # languages
  - name: rustup
  - name: flutter
  - name: python
  - name: nodejs
  - name: go
  - name: openjdk
    bucket: java
  # dev tools
  - name: pnpm
  - name: uv
  - name: ruff
  - name: protobuf
    bucket: extras
  - name: ripgrep
  - name: eza
    bucket: extras
  # IDEs
  - name: zed
    desktop_shortcut: true
  - name: vscode
    bucket: extras
    desktop_shortcut: true
  - name: antigravity
    bucket: extras
    desktop_shortcut: true
  - name: idea
    bucket: extras
    desktop_shortcut: true
