post_setup_commands:
  - irm https://claude.ai/install.ps1 | iex

apps:
  - name: git
  - name: gh
  - name: 7zip
  - name: clash-verge-rev
    bucket: extras
    desktop_shortcut: true

  - name: pwsh
  - name: windows-terminal
    bucket: extras
    desktop_shortcut: true
  - name: k-lite-codec-pack-basic-np
    bucket: extras
  - name: diskgenius
    bucket: extras
    desktop_shortcut: true
  - name: everything
    bucket: extras

  - name: Readest
    bucket: extras
    desktop_shortcut: true
  - name: googlechrome
    bucket: extras
    desktop_shortcut: true
  - name: firefox
    bucket: extras
    desktop_shortcut: true
  - name: obsidian
    bucket: extras
    desktop_shortcut: true

  - name: localsend
    bucket: extras
    desktop_shortcut: true
  - name: enpass
    bucket: extras
  - name: windowsdesktop-runtime-lts
    bucket: extras
  - name: stranslate
    bucket: extras
    desktop_shortcut: true

  # languages
  - name: rustup

  - name: flutter

  - name: python
  - name: uv
  - name: ruff

  - name: nodejs
  - name: bun
  - name: pnpm

  - name: go

  - name: openjdk
    bucket: java
  - name: maven

  # dev tools

  - name: protobuf
    bucket: extras
  - name: tokei
  - name: ripgrep
  - name: eza
    bucket: extras
  - name: cc-switch
    bucket: extras
    desktop_shortcut: true
  - name: codex
    desktop_shortcut: true
  - name: antigravity
    bucket: extras
    desktop_shortcut: true
  - name: antigravity-cli
  # IDEs
  - name: zed
    desktop_shortcut: true
  - name: vscode
    bucket: extras
    desktop_shortcut: true
  - name: idea
    bucket: extras
    desktop_shortcut: true
  - name: antigravity-ide
    bucket: extras
    desktop_shortcut: true
